export const projects = [
    {
        title: "Flikk ",
        description: "A sports application where coaches or clubs can add their own sessions, and the trainees can participate in these sessions.",
        image: "/images/Flikk.png",
        tags: ["Laravel", "MYSQL", "Twilio", 'Tap', 'Backpack'],
        // source: 'https://google.com',
        // visit: "https://medicaljob.me/#/",
        id: 1,
    },
    {
        title: "Medical Job",
        description: "A medical application, in which there are two types of users, and they are hospital owners and doctors, so that the hospital sends a request to search for doctors, and then assigns appropriate specialized doctors to request the hospital and builds a communication process between them through Zoom Meeting.",
        image: "/images/medical.png",
        tags: ["Laravel", "MYSQL", "Mails", 'eSignature', 'Backpack'],
        // source: 'https://google.com',
        visit: "https://medicaljob.me/#/",
        id: 2,
    },
    {
        title: "Katrani",
        description: "A laboratory medical analysis application that helps users request a laboratory to come to the house and perform the necessary medical analysis.",
        image: "/images/payless2.jpg",
        tags: ["Laravel", "MYSQL", "Mails", 'eSignature', 'Backpack'],
        // source: 'https://google.com',
        // visit: "https://google.com",
        id: 3,
    },
    {
        title: "Al-Rifai",
        description:
            "BusyHive is a platform for connecting job posters and job seekers, where the poster can post there jobs as a online or physical job and the seeker can make offers for these jobs an continue in the job lifecycle.",
        image: "/images/refaia2.png",
        tags: ["Laravel", "MYSQL", "Blade", 'Twilio', 'Firebase Notification'],
        // source: 'https://google.com',
        // visit: "https://google.com",
        id: 4,
    },
    // {
    //     title: "Wenha",
    //     description:
    //         "An application that helps people search for their lost items or add posts about things they have to help others. I use Laravel and working on blade to build the admin panel. ",
    //     image: "/images/bcc.png",
    //     tags: ["Laravel", "MYSQL", "Blade", 'Firebase Notification'],
    //     // source: 'https://google.com',
    //     // visit: "http://185.194.126.67:8004/BCC",
    //     id: 5,
    // },
    {
        title: "Eshhanli",
        description: "An application for the delivery of items, where the user adds a request and the driver comes to take the request from the requester and send it to the required place. I use Laravel and working on blade to  build the admin panel",
        image: "/images/eshhanli.jpg",
        tags: ["Laravel", "MYSQL", "Blade", 'Firebase Notification'],
        // source: 'https://google.com',
        // visit: "https://google.com",
        id: 6,
    },
    {
        title: "MIALYSI",
        description: "Mialysi is an HR Management software that provides solutions to companies of all sizes. It offers eight main modules, including employee general information, time tracking, payroll management, invoicing, task management, recruitment, performance management, and learning management.",
        image: "/images/mialysi.png",
        tags: ["Laravel", "MYSQL", 'eSignature', 'Blade', 'Pusher', 'Chats', 'Zoom'],
        // source: 'https://google.com',
        visit: "https://dev.mialysi.com/",
        id: 7,
    },
    {
        title: "QAFF ",
        description: "Qaff connects companies and project owners with professional freelancers, while also providing freelancers a platform to find projects and increase their income.",
        image: "/images/qaff.png",
        tags: ["Laravel", "MYSQL", 'Hyperpay', 'Twilio'],
        // source: 'https://google.com',
        visit: "https://qaff-front.icetulip.com/",
        id: 8,
    },
    {
        title: "JIMI",
        description: "An application that provides all services or selling car and mobile products.",
        image: "/images/jimi.png",
        tags: ["Laravel", "MYSQL", 'Backpack'],
        // source: 'https://google.com',
        visit: "https://google.com",
        id: 9,
    },
    {
        title: "Balance",
        description: "An application to sell all kinds of coffee and display new offers, in addition to the delivery process",
        image: "/images/balance.png",
        tags: ["Laravel", "MYSQL", 'Backpack'],
        // source: 'https://google.com',
        visit: "https://google.com",
        id: 10,
    },
    {
        title: "Cham Wings Bot",
        description:
            "A Chatbot for answering customer questions, booking, and Inquiring about nearest trips. The admin controls this chatbot to update Intents, FAQs, and chat stories.",
        image: "/images/bot.png",
        tags: ["Django", "RASA", "Tensorflow", "React.js"],
        // source: 'https://google.com',
        // visit: 'https://google.com',
        id: 11,
    },
    {
        title: "Self Driving Car",
        description:
            "A prototype of a self-driving car using AI technologies, was built by Raspberry Pi powered by Robotic Operating System (ROS).",
        image: "/images/car.jpg",
        tags: ["ROS", "Linux", "Python", "Raspberry pi"],
        // source: 'https://google.com',
        // visit: 'https://google.com',
        id: 12,
    },

    {
        title: "Game-Hub",
        description: "Small gmae hub that show all  the categories of games.",
        image: "/images/game-hub.png",
        tags: ["React.js", "Typescript"],
        // source: 'https://google.com',
        visit: 'https://game-hub-seven-blond.vercel.app/',
        id: 13,
    },
    {
        title: "Medpush",
        description: "It is a system that performs statistical operations based on surveys that are filled out by customers.",
        // image: "/images/payless2.jpg",
        tags: ["Laravel", "MYSQL", 'Backpack', 'Excel Sheets'],
        // source: 'https://google.com',
        // visit: "https://google.com",
        id: 15,
    },
    {
        title: "Glass",
        description: "Building a control panel through which the company automates the billing process",
        // image: "/images/payless2.jpg",
        tags: ["Laravel", "MYSQL", 'React.js'],
        // source: 'https://google.com',
        // visit: "https://google.com",
        id: 15,
    },
    {
        title: "Afnan",
        description: "Ecommerce shop.",
        // image: "/images/car.jpg",
        tags: ["Node.js", "React.js", "Sequelize"],
        // source: 'https://google.com',
        // visit: 'https://google.com',
        id: 16,
    },

];

export const TimeLineData = [
    {year: 2018, text: "Started my journey as IT student"},
    {year: 2020, text: "Specialized in Artificial Intelligence"},
    {year: 2021, text: "Worked as Laravel and Node JS developer"},
    {year: 2023, text: "Start working with React.js and"},
];
